### PR TITLE
Configure prettier for this project.

### LINKED ISSUE #23: Add prettier or other such formatter
## Description
Configure `prettier` for this project.

### PR DESCRIPTION
**Pull request by anshul137**
Closes #23 

## Description 

Added the [Prettier](https://prettier.io/) into this project

- In `.vscode` folder 
- In `extensions.json` file added [Prettier](https://prettier.io/)  as the recommendation
- In `settings.json` added configration.
-  Run [Prettier](https://prettier.io/) via  command line `npm run format`.
- Check  all the files are formatted via command line `npm run format:check`
-  Added `.prettierignore` 
- Added `.prettierrc.json`
- Update the `CONTRIBUTING.md` on how to use  [Prettier](https://prettier.io/) via  command line

### CODE REVIEW

**Review by SerpentBytes — CHANGES_REQUESTED** [review]
I understand that pushing an empty config file will let the IDE know that we are using `prettier`, but some content should be in the file. Maybe options such as `tabWidth`, since I see its equivalent in `settings.json`. Also, I think you could safely add `singleQuote` and `semi` options to `prettierrc.json`. It should not break the code.

**Comment by anshul137** [comment]
Thanks for the review @SerpentBytes 
Quick question 
 so you want me to move the all the configration from `settings.json` to `prettierrc.json`.  
 and add more options right?

**Comment by SerpentBytes** [comment]
It seems like what you need is also being added in #22. Could you collaborate with @sfrunza13 so that when we merge #22  and #24, there's only a single `prettier` configuration for the codebase? Please, and thank you.

**Comment by SerpentBytes** [comment]
> Thanks for the review @SerpentBytes
> Quick question
> so you want me to move the all the configration from `settings.json` to `prettierrc.json`.
> and add more options right?

Just add the `options` to `prettierrc` needed for this project, based on the project `dependencies`.
`settings.json` is fine.

**Comment by sfrunza13** [comment]
> It seems like what you need is also being added in #22. Could you collaborate with @sfrunza13 so that when we merge #22 and #24, there's only a single `prettier` configuration for the codebase? Please, and thank you.

@anshul137 The .prettierrc.js file is a config file for prettier that we can commit to ensure it behaves in the way we want it to for anyone who decides to work on the project. Feel free to take the one I have written in my PR and add to yours. I am pretty sure .json also works as a format for the prettierrc file, however I would not commit the .vscode folder as it has to do with the editors settings and not the project I believe.

**Comment by SerpentBytes** [comment]
@anshul137 could you please make the requested adjustments? Also, please resolve any merge conflicts.

**Comment by anshul137** [comment]
@SerpentBytes  yes i will work on it and fix the conflict 
Thanks

**Review by SerpentBytes — APPROVED** [review]

**Comment by anshul137** [comment]
> @anshul137 could you please make the requested adjustments? Also, please resolve any merge conflicts.

@SerpentBytes  can you please check and let me know if it need any changes i have resolved the conflict in merge as well.
Thanks

**Review by LostButton — APPROVED** [review]

**Review by batunpc — APPROVED** [review]

**Comment by anshul137** [comment]
@SerpentBytes  Can you merge  pull request ?

**Pull request merged**
