### PR TITLE
Added linting

### LINKED ISSUE #21: Add linting and preliminary workflow for CI

### PR DESCRIPTION
**Pull request by sfrunza13**
Added linting
Separated export from function components and added Prop Type Validation
Added github actions workflow for linting

closes #21

### CODE REVIEW

**Review by SerpentBytes — CHANGES_REQUESTED** [review]
Could you please format it using a formatting tool like `prettier`? 

I would appreciate it if you could file an issue about the missing `prettier` configuration, as well.

**Comment by SerpentBytes** [comment]
@sfrunza13 Also, could you update the `CONTRIBUTING.md` file with information on how to check for `lint` errors?

**Comment by sfrunza13** [comment]
> @sfrunza13 Also, could you update the `CONTRIBUTING.md` file with information on how to check for `lint` errors?

added prettier and to Contributing md

**Review by SerpentBytes — CHANGES_REQUESTED** [review]
There are some problems:

- We currently have two PRs. One for adding a linter (#22) and another for adding a formatter (#24) 
- Prettier configuration for the codebase is outside the scope of this PR, as it is related to ( #24). Merging (#22) and (#24) will add `prettier` twice to the project. I requested you to only format your code.
- Finally, there's a merge conflict that needs to be resolved. It seems like you  are formatting `package*.json` files, somehow, even though you are ignoring them in `.prettierignore`. Maybe the IDE is doing it?

**Comment by sfrunza13** [comment]
continued in [25](https://github.com/humphd/my-photohub/pull/25/files)

**Pull request closed without merging**
