### PR TITLE
chore: package.json updated with scripts

### PR DESCRIPTION
**Pull request by batunpc**

### CODE REVIEW

**Review by SerpentBytes — COMMENTED** [review]
@batunpc I have added my scripts.

**Review by batunpc — COMMENTED** [review]
Do we have all the scripts ?

**Comment by SerpentBytes** [comment]
@LostButton, could you check to see if your scripts are in? If they are not, could you add them?

**Comment by LostButton** [comment]
Do we need my scripts?

**Comment by SerpentBytes** [comment]
> Do we need my scripts? Cause mine would overlay with the others

We don't need to add yours, as users would never interact directly with the gallery. 
They would have to go throw the authentication and repo creation process introduced in #1 first and then successfully upload photos to the repo. We are not quite there yet. 

@batunpc, I think it's safe to merge the changes we have committed.

**Comment by batunpc** [comment]
> > Do we need my scripts? Cause mine would overlay with the others
> 
> We don't need to add yours, as users would never interact directly with the gallery. They would have to go throw the authentication and repo creation process introduced in #1 first and then successfully upload photos to the repo. We are not quite there yet.
> 
> @batunpc, I think it's safe to merge the changes we have committed.

Okay just wanted to make sure, merging it now !

**Pull request merged**
